server:
  port: 8081

spring:
  application:
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie
#      username: root
#      password: "000000"
  shardingsphere:
    datasource:
      names: master,slave
      #主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.100:3306/reggie
        username: root
        password: "000000"

      #从主数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.150:3306/reggie
        username: root
        password: "000000"
    masterslave:
      load-balance-algorithm-type: round_robin
      name: dataSource
      slave-data-source-names: slave
      master-data-source-name: master
    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      # 设置支持的单个上传文件的大小限制
      max-file-size: 2MB
      # 设置最大的请求文件大小，设置总体大小请求
      max-request-size: 10MB
      # 临时路径
      location: /
      # 文件写入磁盘的阈值
      file-size-threshold: 0B
  redis:
    port: 6379
    host: localhost
    database: 0
  cache:
    redis:
      # 设置缓存过期时间
      time-to-live: 180000
#    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # \u914D\u7F6E\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

reggie:
  path: /usr/local/app/img/

